//
//  StatesStruct.swift
//  schoolFinder
//
//  Created by Jonathan Yu on 2/12/16.
//  Copyright © 2016 Jonathan Yu. All rights reserved.
//

import Foundation

class OptionSettings: NSObject {
    
    var statesNumCodes: [String: Int] = [
        "Alabama": 1,
        "Alaska": 2,
        "Arizona": 4,
        "Arkansas": 5,
        "California": 6,
        "Colorado": 8,
        "Connecticut": 9,
        "Delaware": 10,
        "District of Columbia": 11,
        "Florida": 12,
        "Georgia": 13,
        "Hawaii": 15,
        "Idaho": 16,
        "Illinois": 17,
        "Indiana": 18,
        "Iowa": 19,
        "Kansas": 20,
        "Kentucky": 21,
        "Louisiana": 22,
        "Maine": 23,
        "Maryland": 24,
        "Massachusetts": 25,
        "Michigan": 26,
        "Minnesota": 27,
        "Mississippi": 28,
        "Missouri": 29,
        "Montana": 30,
        "Nebraska": 31,
        "Nevada": 32,
        "New Hampshire": 33,
        "New Jersey": 34,
        "New Mexico": 35,
        "New York": 36,
        "North Carolina": 37,
        "North Dakota": 38,
        "Ohio": 39,
        "Oklahoma": 40,
        "Oregon": 41,
        "Pennsylvania": 42,
        "Rhode Island": 44,
        "South Carolina": 45,
        "South Dakota": 46,
        "Tennessee": 47,
        "Texas": 48,
        "Utah": 49,
        "Vermont": 50,
        "Virginia": 51,
        "Washington": 53,
        "West Virginia": 54,
        "Wisconsin": 55,
        "Wyoming": 56,
        "American Samoa": 60,
        "Federated States of Micronesia": 64,
        "Guam": 66,
        "Northern Mariana Islands": 69,
        "Palau": 70,
        "Puerto Rico": 72,
        "Virgin Islands": 78,
    ]
    
    var stateSettings: [String: String] = [
        "Alabama": "AL",
        "Alaska": "AK",
        "American Samoa": "AS",
        "Arizona": "AZ",
        "Arkansas": "AR",
        "California": "CA",
        "Colorado": "CO",
        "Connecticut": "CT",
        "Delaware": "DE",
        "Dist. of Columbia": "DC",
        "Florida": "FL",
        "Georgia": "GA",
        "Guam": "GU",
        "Hawaii": "HI",
        "Idaho": "ID",
        "Illinois": "IL",
        "Indiana": "IN",
        "Iowa": "IA",
        "Kansas": "KS",
        "Kentucky": "KY",
        "Louisiana": "LA",
        "Maine": "ME",
        "Maryland": "MD",
        "Marshall Islands": "MH",
        "Massachusetts": "MA",
        "Michigan": "MI",
        "Micronesia": "FM",
        "Minnesota": "MN",
        "Mississippi": "MS",
        "Missouri": "MO",
        "Montana": "MT",
        "Nebraska": "NE",
        "Nevada": "NV",
        "New Hampshire": "NH",
        "New Jersey": "NJ",
        "New Mexico": "NM",
        "New York": "NY",
        "North Carolina": "NC",
        "North Dakota": "ND",
        "Northern Marianas": "MP",
        "Ohio": "OH",
        "Oklahoma": "OK",
        "Oregon": "OR",
        "Palau": "PW",
        "Pennsylvania": "PA",
        "Puerto Rico": "PR",
        "Rhode Island": "RI",
        "South Carolina": "SC",
        "South Dakota": "SD",
        "Tennessee": "TN",
        "Texas": "TX",
        "Utah": "UT",
        "Vermont": "VT",
        "Virginia": "VA",
        "Virgin Islands": "VI",
        "Washington": "WA",
        "West Virginia": "WV",
        "Wisconsin": "WI",
        "Wyoming": "WY"
    ]
    
    var carnegieSizeSettings: [String: String] = [
        "Very small 2-year (confers associate’s degrees, FTE enrollment less than 500)": "1",
        "Small 2-year (confers associate’s degrees, FTE enrollment 500 to 1,999)": "2",
        "Medium 2-year (confers associate’s degrees, FTE enrollment 2000 to 4,999)": "3",
        "Large 2-year (confers associate’s degrees, FTE enrollment 5000 to 9,999)": "4",
        "Very large 2-year (confers associate’s degrees, FTE enrollment 10,000 or more)": "5",
        "Very small 4-year, primarily nonresidential (confers bachelor’s degrees, FTE enrollment less than 1,000, less than 25 percent of degree-seeking undergraduates live on campus and/or less than 50 percent attend full time)": "6",
        "Very small 4-year, primarily residential (confers bachelor’s degrees, FTE enrollment less than 1,000, 25 to 49 percent of degree-seeking undergraduates live on campus and at least 50 percent attend full time)": "7",
        "Very small 4-year, highly residential (confers bachelor’s degrees, FTE enrollment less than 1,000, at least 50 percent of degree-seeking undergraduates live on campus and at least 80 percent attend full time)": "8",
        "Small 4-year, primarily nonresidential (confers bachelor’s degrees, FTE enrollment 1,000 to 2,999, less than 25 percent of degree-seeking undergraduates live on campus and/or less than 50 percent attend full time)": "9",
        "Small 4-year, primarily residential (confers bachelor’s degrees, FTE enrollment 1,000 to 2,999, 25 to 49 percent of degree-seeking undergraduates live on campus and at least 50 percent attend full time)": "10",
        "Small 4-year, highly residential (confers bachelor’s degrees, FTE enrollment 1,000 to 2,999, at least 50 percent of degree-seeking undergraduates live on campus and at least 80 percent attend full time)": "11",
        "Medium 4-year, primarily nonresidential (confers bachelor’s degrees, FTE enrollment 3,000 to 9,999, less than 25 percent of degree-seeking undergraduates live on campus and/or less than 50 percent attend full time)": "12",
        "Medium 4-year, primarily residential (confers bachelor’s degrees, FTE enrollment 3,000 to 9,999, 25 to 49 percent of degree-seeking undergraduates live on campus and at least 50 percent attend full time)": "13",
        "Medium 4-year, highly residential (confers bachelor’s degrees, FTE enrollment 3,000 to 9,999, at least 50 percent of degree-seeking undergraduates live on campus and at least 80 percent attend full time)": "14",
        "Large 4-year, primarily nonresidential (confers bachelor’s degrees, FTE enrollment over 9,999, less than 25 percent of degree-seeking undergraduates live on campus and/or less than 50 percent attend full time)": "15",
        "Large 4-year, primarily residential (confers bachelor’s degrees, FTE enrollment over 9,999, 25 to 49 percent of degree-seeking undergraduates live on campus and at least 50 percent attend full time)": "16",
        "Large 4-year, highly residential (confers bachelor’s degrees, FTE enrollment over 9,999, at least 50 percent of degree-seeking undergraduates live on campus and at least 80 percent attend full time)": "17",
        "Not applicable, special-focus institution": "18"
    ]
    
    var localeSettings: [String: String] = [
        "City: Large (population of 250,000 or more)": "11",
        "City: Midsize (population of at least 100,000 but less than 250,000)": "12",
        "City: Small (population less than 100,000)": "13",
        "Suburb: Large (outside principal city, in urbanized area with population of 250,000 or more)": "21",
        "Suburb: Midsize (outside principal city, in urbanized area with population of at least 100,000 but less than 250,000)": "22",
        "Suburb: Small (outside principal city, in urbanized area with population less than 100,000)": "23",
        "Town: Fringe (in urban cluster up to 10 miles from an urbanized area)": "31",
        "Town: Distant (in urban cluster more than 10 miles and up to 35 miles from an urbanized area)": "32",
        "Town: Remote (in urban cluster more than 35 miles from an urbanized area)": "33",
        "Rural: Fringe (rural territory up to 5 miles from an urbanized area or up to 2.5 miles from an urban cluster)": "41",
        "Rural: Distant (rural territory more than 5 miles but up to 25 miles from an urbanized area or more than 2.5 and up to 10 miles from an urban cluster)": "42",
        "Rural: Remote (rural territory more than 25 miles from an urbanized area and more than 10 miles from an urban cluster)": "43"
    ]
    
    var carnegieBasicSettings: [String: String] = [
        "Not classified": "0",
        "Associate's--Public Rural-serving Small": "1",
        "Associate's--Public Rural-serving Medium": "2",
        "Associate's--Public Rural-serving Large": "3",
        "Associate's--Public Suburban-serving Single Campus": "4",
        "Associate's--Public Suburban-serving Multicampus": "5",
        "Associate's--Public Urban-serving Single Campus": "6",
        "Associate's--Public Urban-serving Multicampus": "7",
        "Associate's--Public Special Use": "8",
        "Associate's--Private Not-for-profit": "9",
        "Associate's--Private For-profit": "10",
        "Associate's--Public 2-year colleges under 4-year universities": "11",
        "Associate's--Public 4-year Primarily Associate's": "12",
        "Associate's--Private Not-for-profit 4-year Primarily Associate's": "13",
        "Associate's--Private For-profit 4-year Primarily Associate's": "14",
        "Research Universities (very high research activity)": "15",
        "Research Universities (high research activity)": "16",
        "Doctoral/Research Universities": "17",
        "Master's Colleges and Universities (larger programs)": "18",
        "Master's Colleges and Universities (medium programs)": "19",
        "Master's Colleges and Universities (smaller programs)": "20",
        "Baccalaureate Colleges--Arts & Sciences": "21",
        "Baccalaureate Colleges--Diverse Fields": "22",
        "Baccalaureate/Associate's Colleges": "23",
        "Special Focus Institutions--Theological seminaries, Bible colleges, and other faith-related institutions": "24",
        "Special Focus Institutions--Medical schools and medical centers": "25",
        "Special Focus Institutions--Other health professions schools": "26",
        "Special Focus Institutions--Schools of engineering": "27",
        "Special Focus Institutions--Other technology-related schools": "28",
        "Special Focus Institutions--Schools of business and management": "29",
        "Special Focus Institutions--Schools of art, music, and design": "30",
        "Special Focus Institutions--Schools of law": "31",
        "Special Focus Institutions--Other special-focus institutions": "32",
        "Tribal Colleges": "33"
    ]
    
    var stateFirstLetters = [
        "A",
        "C",
        "D",
        "F",
        "G",
        "H",
        "I",
        "K",
        "L",
        "M",
        "N",
        "O",
        "P",
        "R",
        "S",
        "T",
        "U",
        "V",
        "W"
    ]
    
    var dataFieldsDefinitions: [String: String] = [
        "id": "Unit ID for institution",
        "ope8_id": "8-digit OPE ID for institution",
        "ope6_id": "6-digit OPE ID for institution",
        "name": "Institution name",
        "city": "City",
        "state": "State postcode",
        "zip": "ZIP code",
        "accreditor": "Accreditor for institution",
        "school_url": "URL for institution's homepage",
        "price_calculator_url": "URL for institution's net price calculator",
        "degrees_awarded.predominant_recoded": "Predominant degree awarded (recoded 0s and 4s)",
        "main_campus": "Flag for main campus",
        "branches": "Number of branch campuses",
        "degrees_awarded.predominant": "Predominant degree awarded",
        "ownership": "Control of institution",
        "state_fips": "FIPS code for state",
        "region_id": "Region (IPEDS)",
        "locale": "Locale of institution",
        "degree_urbanization": "Degree of urbanization of institution",
        "lat": "Latitude",
        "lon": "Longitude",
        "carnegie_basic": "Carnegie Classification -- basic",
        "degrees_awarded.highest": "Highest degree awarded",
    ]
    
    var dataValuesDefinitions: [String: [String: String]] = [
        "degrees_awarded.highest": [
            "1": "Certificate degree",
            "2": "Associate degree",
            "3": "Bachelor's degree",
            "4": "Graduate degree"
        ],
        "degrees_awarded.predominant_recoded": [
            "1": "Certificate degree",
            "2": "Associate degree",
            "3": "Bachelor's degree",
            "4": "Graduate degree"
        ],
        "ownership": [
            "1": "Public",
            "2": "Private nonprofit",
            "3": "Private for-profit"
        ],
        "region_id": [
            "1": "New England (CT, ME, MA, NH, RI, VT)",
            "2": "Mid East (DE, DC, MD, NJ, NY, PA)",
            "3": "Great Lakes (IL, IN, MI, OH, WI)",
            "4": "Plains (IA, KS, MN, MO, NE, ND, SD)",
            "5": "Southeast (AL, AR, FL, GA, KY, LA, MS, NC, SC, TN, VA, WV)",
            "6": "Southwest (AZ, NM, OK, TX)",
            "7": "Rocky Mountains (CO, ID, MT, UT, WY)",
            "8": "Far West (AK, CA, HI, NV, OR, WA)",
            "9": "Outlying Areas (AS, FM, GU, MH, MP, PR, PW, VI)"
        ],
        "locale": [
            "11": "City: Large (population of 250,000 or more)",
            "12": "City: Midsize (population of at least 100,000 but less than 250,000)",
            "13": "City: Small (population less than 100,000)",
            "21": "Suburb: Large (outside principal city, in urbanized area with population of 250,000 or more)",
            "22": "Suburb: Midsize (outside principal city, in urbanized area with population of at least 100,000 but less than 250,000)",
            "23": "Suburb: Small (outside principal city, in urbanized area with population less than 100,000)",
            "31": "Town: Fringe (in urban cluster up to 10 miles from an urbanized area)",
            "32": "Town: Distant (in urban cluster more than 10 miles and up to 35 miles from an urbanized area)",
            "33": "Town: Remote (in urban cluster more than 35 miles from an urbanized area)",
            "41": "Rural: Fringe (rural territory up to 5 miles from an urbanized area or up to 2.5 miles from an urban cluster)",
            "42": "Rural: Distant (rural territory more than 5 miles but up to 25 miles from an urbanized area or more than 2.5 and up to 10 miles from an urban cluster)",
            "43": "Rural: Remote (rural territory more than 25 miles from an urbanized area and more than 10 miles from an urban cluster)"
        ],
        "degree_urbanization": [
            "1": "Large City (a central city of a CMSA or MSA, with the city having a population greater than or equal to 250,000)",
            "2": "Mid-Size City (a central city of a CMSA or MSA, with the city having a population less than 250,000)",
            "3": "Urban Fringe of a Large City (any territory within a CMSA or MSA of a Large City and defined as urban by the Census Bureau)",
            "4": "Urban Fringe of a Mid-Size City (any territory within a CMSA or MSA of a Mid-Size City and defined as urban by the Census Bureau)",
            "5": "Large Town (an incorporated place or Census-designated place with a population greater than or equal to 25,000 and located outside a CMSA or MSA)",
            "6": "Small Town (an incorporated place or Census-designated place with a population less than 25,000 and greater than or equal to 2,500 and located outside a CMSA or MSA)",
            "7": "Rural, Outside MSA (any territory designated as rural by the Census Bureau that is outside a CMSA or MSA of a Large or Mid-Size City)",
            "8": "Rural, Inside MSA (any territory designated as rural by the Census Bureau that is within a CMSA or MSA of a Large or Mid-Size City)"
        ],
        "carnegie_basic": [
            "0": "Not classified",
            "1": "Associate's--Public Rural-serving Small",
            "2": "Associate's--Public Rural-serving Medium",
            "3": "Associate's--Public Rural-serving Large",
            "4": "Associate's--Public Suburban-serving Single Campus",
            "5": "Associate's--Public Suburban-serving Multicampus",
            "6": "Associate's--Public Urban-serving Single Campus",
            "7": "Associate's--Public Urban-serving Multicampus",
            "8": "Associate's--Public Special Use",
            "9": "Associate's--Private Not-for-profit",
            "10": "Associate's--Private For-profit",
            "11": "Associate's--Public 2-year colleges under 4-year universities",
            "12": "Associate's--Public 4-year Primarily Associate's",
            "13": "Associate's--Private Not-for-profit 4-year Primarily Associate's",
            "14": "Associate's--Private For-profit 4-year Primarily Associate's",
            "15": "Research Universities (very high research activity)",
            "16": "Research Universities (high research activity)",
            "17": "Doctoral/Research Universities",
            "18": "Master's Colleges and Universities (larger programs)",
            "19": "Master's Colleges and Universities (medium programs)",
            "20": "Master's Colleges and Universities (smaller programs)",
            "21": "Baccalaureate Colleges--Arts & Sciences",
            "22": "Baccalaureate Colleges--Diverse Fields",
            "23": "Baccalaureate/Associate's Colleges",
            "24": "Special Focus Institutions--Theological seminaries, Bible colleges, and other faith-related institutions",
            "25": "Special Focus Institutions--Medical schools and medical centers",
            "26": "Special Focus Institutions--Other health professions schools",
            "27": "Special Focus Institutions--Schools of engineering",
            "28": "Special Focus Institutions--Other technology-related schools",
            "29": "Special Focus Institutions--Schools of business and management",
            "30": "Special Focus Institutions--Schools of art, music, and design",
            "31": "Special Focus Institutions--Schools of law",
            "32": "Special Focus Institutions--Other special-focus institutions",
            "33": "Tribal Colleges"
        ],
        "carnegie_size_setting": [
            "1": "Very small 2-year (confers associate’s degrees, FTE enrollment less than 500)",
            "2": "Small 2-year (confers associate’s degrees, FTE enrollment 500 to 1,999)",
            "3": "Medium 2-year (confers associate’s degrees, FTE enrollment 2000 to 4,999)",
            "4": "Large 2-year (confers associate’s degrees, FTE enrollment 5000 to 9,999)",
            "5": "Very large 2-year (confers associate’s degrees, FTE enrollment 10,000 or more)",
            "6": "Very small 4-year, primarily nonresidential (confers bachelor’s degrees, FTE enrollment less than 1,000, less than 25 percent of degree-seeking undergraduates live on campus and/or less than 50 percent attend full time)",
            "7": "Very small 4-year, primarily residential (confers bachelor’s degrees, FTE enrollment less than 1,000, 25 to 49 percent of degree-seeking undergraduates live on campus and at least 50 percent attend full time)",
            "8": "Very small 4-year, highly residential (confers bachelor’s degrees, FTE enrollment less than 1,000, at least 50 percent of degree-seeking undergraduates live on campus and at least 80 percent attend full time)",
            "9": "Small 4-year, primarily nonresidential (confers bachelor’s degrees, FTE enrollment 1,000 to 2,999, less than 25 percent of degree-seeking undergraduates live on campus and/or less than 50 percent attend full time)",
            "10": "Small 4-year, primarily residential (confers bachelor’s degrees, FTE enrollment 1,000 to 2,999, 25 to 49 percent of degree-seeking undergraduates live on campus and at least 50 percent attend full time)",
            "11": "Small 4-year, highly residential (confers bachelor’s degrees, FTE enrollment 1,000 to 2,999, at least 50 percent of degree-seeking undergraduates live on campus and at least 80 percent attend full time)",
            "12": "Medium 4-year, primarily nonresidential (confers bachelor’s degrees, FTE enrollment 3,000 to 9,999, less than 25 percent of degree-seeking undergraduates live on campus and/or less than 50 percent attend full time)",
            "13": "Medium 4-year, primarily residential (confers bachelor’s degrees, FTE enrollment 3,000 to 9,999, 25 to 49 percent of degree-seeking undergraduates live on campus and at least 50 percent attend full time)",
            "14": "Medium 4-year, highly residential (confers bachelor’s degrees, FTE enrollment 3,000 to 9,999, at least 50 percent of degree-seeking undergraduates live on campus and at least 80 percent attend full time)",
            "15": "Large 4-year, primarily nonresidential (confers bachelor’s degrees, FTE enrollment over 9,999, less than 25 percent of degree-seeking undergraduates live on campus and/or less than 50 percent attend full time)",
            "16": "Large 4-year, primarily residential (confers bachelor’s degrees, FTE enrollment over 9,999, 25 to 49 percent of degree-seeking undergraduates live on campus and at least 50 percent attend full time)",
            "17": "Large 4-year, highly residential (confers bachelor’s degrees, FTE enrollment over 9,999, at least 50 percent of degree-seeking undergraduates live on campus and at least 80 percent attend full time)",
            "18": "Not applicable, special-focus institution"
        ],
        "religious_affiliation": [
            "-1": "Not reported",
            "-2": "Not applicable",
            "22": "American Evangelical Lutheran Church",
            "24": "African Methodist Episcopal Zion Church",
            "27": "Assemblies of God Church",
            "28": "Brethren Church",
            "30": "Roman Catholic",
            "33": "Wisconsin Evangelical Lutheran Synod",
            "34": "Christ and Missionary Alliance Church",
            "35": "Christian Reformed Church",
            "36": "Evangelical Congregational Church",
            "37": "Evangelical Covenant Church of America",
            "38": "Evangelical Free Church of America",
            "39": "Evangelical Lutheran Church",
            "40": "International United Pentecostal Church",
            "41": "Free Will Baptist Church",
            "42": "Interdenominational",
            "43": "Mennonite Brethren Church",
            "44": "Moravian Church",
            "45": "North American Baptist",
            "47": "Pentecostal Holiness Church",
            "48": "Christian Churches and Churches of Christ",
            "49": "Reformed Church in America",
            "50": "Episcopal Church, Reformed",
            "51": "African Methodist Episcopal",
            "52": "American Baptist",
            "53": "American Lutheran",
            "54": "Baptist",
            "55": "Christian Methodist Episcopal",
            "57": "Church of God",
            "58": "Church of Brethren",
            "59": "Church of the Nazarene",
            "60": "Cumberland Presbyterian",
            "61": "Christian Church (Disciples of Christ)",
            "64": "Free Methodist",
            "65": "Friends",
            "66": "Presbyterian Church (USA)",
            "67": "Lutheran Church in America",
            "68": "Lutheran Church - Missouri Synod",
            "69": "Mennonite Church",
            "71": "United Methodist",
            "73": "Protestant Episcopal",
            "74": "Churches of Christ",
            "75": "Southern Baptist",
            "76": "United Church of Christ",
            "77": "Protestant, not specified",
            "78": "Multiple Protestant Denomination",
            "79": "Other Protestant",
            "80": "Jewish",
            "81": "Reformed Presbyterian Church",
            "84": "United Brethren Church",
            "87": "Missionary Church Inc",
            "88": "Undenominational",
            "89": "Wesleyan",
            "91": "Greek Orthodox",
            "92": "Russian Orthodox",
            "93": "Unitarian Universalist",
            "94": "Latter Day Saints (Mormon Church)",
            "95": "Seventh Day Adventists",
            "97": "The Presbyterian Church in America",
            "99": "Other (none of the above)",
            "100": "Original Free Will Baptist",
            "101": "Ecumenical Christian",
            "102": "Evangelical Christian",
            "103": "Presbyterian"
        ]
        
    ]
}