//
//  StatesStruct.swift
//  schoolFinder
//
//  Created by Jonathan Yu on 2/12/16.
//  Copyright © 2016 Jonathan Yu. All rights reserved.
//

import Foundation

class OptionSettings: NSObject {
    
    var statesNumCodes: [String: Int] = [
        "Alabama": 1,
        "Alaska": 2,
        "Arizona": 4,
        "Arkansas": 5,
        "California": 6,
        "Colorado": 8,
        "Connecticut": 9,
        "Delaware": 10,
        "District of Columbia": 11,
        "Florida": 12,
        "Georgia": 13,
        "Hawaii": 15,
        "Idaho": 16,
        "Illinois": 17,
        "Indiana": 18,
        "Iowa": 19,
        "Kansas": 20,
        "Kentucky": 21,
        "Louisiana": 22,
        "Maine": 23,
        "Maryland": 24,
        "Massachusetts": 25,
        "Michigan": 26,
        "Minnesota": 27,
        "Mississippi": 28,
        "Missouri": 29,
        "Montana": 30,
        "Nebraska": 31,
        "Nevada": 32,
        "New Hampshire": 33,
        "New Jersey": 34,
        "New Mexico": 35,
        "New York": 36,
        "North Carolina": 37,
        "North Dakota": 38,
        "Ohio": 39,
        "Oklahoma": 40,
        "Oregon": 41,
        "Pennsylvania": 42,
        "Rhode Island": 44,
        "South Carolina": 45,
        "South Dakota": 46,
        "Tennessee": 47,
        "Texas": 48,
        "Utah": 49,
        "Vermont": 50,
        "Virginia": 51,
        "Washington": 53,
        "West Virginia": 54,
        "Wisconsin": 55,
        "Wyoming": 56,
        "American Samoa": 60,
        "Federated States of Micronesia": 64,
        "Guam": 66,
        "Northern Mariana Islands": 69,
        "Palau": 70,
        "Puerto Rico": 72,
        "Virgin Islands": 78,
    ]
    
    var stateSettings: [String: String] = [
        "Alabama": "AL",
        "Alaska": "AK",
        "American Samoa": "AS",
        "Arizona": "AZ",
        "Arkansas": "AR",
        "California": "CA",
        "Colorado": "CO",
        "Connecticut": "CT",
        "Delaware": "DE",
        "Dist. of Columbia": "DC",
        "Florida": "FL",
        "Georgia": "GA",
        "Guam": "GU",
        "Hawaii": "HI",
        "Idaho": "ID",
        "Illinois": "IL",
        "Indiana": "IN",
        "Iowa": "IA",
        "Kansas": "KS",
        "Kentucky": "KY",
        "Louisiana": "LA",
        "Maine": "ME",
        "Maryland": "MD",
        "Marshall Islands": "MH",
        "Massachusetts": "MA",
        "Michigan": "MI",
        "Micronesia": "FM",
        "Minnesota": "MN",
        "Mississippi": "MS",
        "Missouri": "MO",
        "Montana": "MT",
        "Nebraska": "NE",
        "Nevada": "NV",
        "New Hampshire": "NH",
        "New Jersey": "NJ",
        "New Mexico": "NM",
        "New York": "NY",
        "North Carolina": "NC",
        "North Dakota": "ND",
        "Northern Marianas": "MP",
        "Ohio": "OH",
        "Oklahoma": "OK",
        "Oregon": "OR",
        "Palau": "PW",
        "Pennsylvania": "PA",
        "Puerto Rico": "PR",
        "Rhode Island": "RI",
        "South Carolina": "SC",
        "South Dakota": "SD",
        "Tennessee": "TN",
        "Texas": "TX",
        "Utah": "UT",
        "Vermont": "VT",
        "Virginia": "VA",
        "Virgin Islands": "VI",
        "Washington": "WA",
        "West Virginia": "WV",
        "Wisconsin": "WI",
        "Wyoming": "WY"
    ]
    
    var carnegieSizeSettings: [String: String] = [
        "Very small 2-year (confers associate’s degrees, FTE enrollment less than 500)": "1",
        "Small 2-year (confers associate’s degrees, FTE enrollment 500 to 1,999)": "2",
        "Medium 2-year (confers associate’s degrees, FTE enrollment 2000 to 4,999)": "3",
        "Large 2-year (confers associate’s degrees, FTE enrollment 5000 to 9,999)": "4",
        "Very large 2-year (confers associate’s degrees, FTE enrollment 10,000 or more)": "5",
        "Very small 4-year, primarily nonresidential (confers bachelor’s degrees, FTE enrollment less than 1,000, less than 25 percent of degree-seeking undergraduates live on campus and/or less than 50 percent attend full time)": "6",
        "Very small 4-year, primarily residential (confers bachelor’s degrees, FTE enrollment less than 1,000, 25 to 49 percent of degree-seeking undergraduates live on campus and at least 50 percent attend full time)": "7",
        "Very small 4-year, highly residential (confers bachelor’s degrees, FTE enrollment less than 1,000, at least 50 percent of degree-seeking undergraduates live on campus and at least 80 percent attend full time)": "8",
        "Small 4-year, primarily nonresidential (confers bachelor’s degrees, FTE enrollment 1,000 to 2,999, less than 25 percent of degree-seeking undergraduates live on campus and/or less than 50 percent attend full time)": "9",
        "Small 4-year, primarily residential (confers bachelor’s degrees, FTE enrollment 1,000 to 2,999, 25 to 49 percent of degree-seeking undergraduates live on campus and at least 50 percent attend full time)": "10",
        "Small 4-year, highly residential (confers bachelor’s degrees, FTE enrollment 1,000 to 2,999, at least 50 percent of degree-seeking undergraduates live on campus and at least 80 percent attend full time)": "11",
        "Medium 4-year, primarily nonresidential (confers bachelor’s degrees, FTE enrollment 3,000 to 9,999, less than 25 percent of degree-seeking undergraduates live on campus and/or less than 50 percent attend full time)": "12",
        "Medium 4-year, primarily residential (confers bachelor’s degrees, FTE enrollment 3,000 to 9,999, 25 to 49 percent of degree-seeking undergraduates live on campus and at least 50 percent attend full time)": "13",
        "Medium 4-year, highly residential (confers bachelor’s degrees, FTE enrollment 3,000 to 9,999, at least 50 percent of degree-seeking undergraduates live on campus and at least 80 percent attend full time)": "14",
        "Large 4-year, primarily nonresidential (confers bachelor’s degrees, FTE enrollment over 9,999, less than 25 percent of degree-seeking undergraduates live on campus and/or less than 50 percent attend full time)": "15",
        "Large 4-year, primarily residential (confers bachelor’s degrees, FTE enrollment over 9,999, 25 to 49 percent of degree-seeking undergraduates live on campus and at least 50 percent attend full time)": "16",
        "Large 4-year, highly residential (confers bachelor’s degrees, FTE enrollment over 9,999, at least 50 percent of degree-seeking undergraduates live on campus and at least 80 percent attend full time)": "17",
        "Not applicable, special-focus institution": "18"
    ]
    
    var localeSettings: [String: String] = [
        "City: Large (population of 250,000 or more)": "11",
        "City: Midsize (population of at least 100,000 but less than 250,000)": "12",
        "City: Small (population less than 100,000)": "13",
        "Suburb: Large (outside principal city, in urbanized area with population of 250,000 or more)": "21",
        "Suburb: Midsize (outside principal city, in urbanized area with population of at least 100,000 but less than 250,000)": "22",
        "Suburb: Small (outside principal city, in urbanized area with population less than 100,000)": "23",
        "Town: Fringe (in urban cluster up to 10 miles from an urbanized area)": "31",
        "Town: Distant (in urban cluster more than 10 miles and up to 35 miles from an urbanized area)": "32",
        "Town: Remote (in urban cluster more than 35 miles from an urbanized area)": "33",
        "Rural: Fringe (rural territory up to 5 miles from an urbanized area or up to 2.5 miles from an urban cluster)": "41",
        "Rural: Distant (rural territory more than 5 miles but up to 25 miles from an urbanized area or more than 2.5 and up to 10 miles from an urban cluster)": "42",
        "Rural: Remote (rural territory more than 25 miles from an urbanized area and more than 10 miles from an urban cluster)": "43"
    ]
    
    var carnegieBasicSettings: [String: String] = [
        "Not classified": "0",
        "Associate's--Public Rural-serving Small": "1",
        "Associate's--Public Rural-serving Medium": "2",
        "Associate's--Public Rural-serving Large": "3",
        "Associate's--Public Suburban-serving Single Campus": "4",
        "Associate's--Public Suburban-serving Multicampus": "5",
        "Associate's--Public Urban-serving Single Campus": "6",
        "Associate's--Public Urban-serving Multicampus": "7",
        "Associate's--Public Special Use": "8",
        "Associate's--Private Not-for-profit": "9",
        "Associate's--Private For-profit": "10",
        "Associate's--Public 2-year colleges under 4-year universities": "11",
        "Associate's--Public 4-year Primarily Associate's": "12",
        "Associate's--Private Not-for-profit 4-year Primarily Associate's": "13",
        "Associate's--Private For-profit 4-year Primarily Associate's": "14",
        "Research Universities (very high research activity)": "15",
        "Research Universities (high research activity)": "16",
        "Doctoral/Research Universities": "17",
        "Master's Colleges and Universities (larger programs)": "18",
        "Master's Colleges and Universities (medium programs)": "19",
        "Master's Colleges and Universities (smaller programs)": "20",
        "Baccalaureate Colleges--Arts & Sciences": "21",
        "Baccalaureate Colleges--Diverse Fields": "22",
        "Baccalaureate/Associate's Colleges": "23",
        "Special Focus Institutions--Theological seminaries, Bible colleges, and other faith-related institutions": "24",
        "Special Focus Institutions--Medical schools and medical centers": "25",
        "Special Focus Institutions--Other health professions schools": "26",
        "Special Focus Institutions--Schools of engineering": "27",
        "Special Focus Institutions--Other technology-related schools": "28",
        "Special Focus Institutions--Schools of business and management": "29",
        "Special Focus Institutions--Schools of art, music, and design": "30",
        "Special Focus Institutions--Schools of law": "31",
        "Special Focus Institutions--Other special-focus institutions": "32",
        "Tribal Colleges": "33"
    ]
    
    var stateFirstLetters = [
        "A",
        "C",
        "D",
        "F",
        "G",
        "H",
        "I",
        "K",
        "L",
        "M",
        "N",
        "O",
        "P",
        "R",
        "S",
        "T",
        "U",
        "V",
        "W"
    ]
}